// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package videoversedb

import (
	"database/sql"
	"time"
)

type SharedLink struct {
	ID        int64
	VideoID   int64
	UserID    int64
	Link      string
	ExpiresAt time.Time
	CreatedAt sql.NullTime
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
}

type Video struct {
	ID            int64
	Title         string
	Description   string
	UserID        int64
	SourceVideoID sql.NullInt64
	Type          string
	FilePath      string
	FileName      sql.NullString
	SizeInBytes   int64
	Duration      int64
	StartTime     sql.NullInt64
	EndTime       sql.NullInt64
	Metadata      sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}
